displayName=Better Farming
author=josephrmartin14
description=Helps with farm runs with icons and tab highlighting by improving on Easy Farming
tags=farming,herb,run,utility,tree,fruit tree
plugins=com.easyfarming.EasyFarmingPlugin
build=standard